### PR TITLE
Feat/w2

### PR DESCRIPTION
**Pull request by vitalytaranov**
https://d1s6wl39sh56na.cloudfront.net

### CODE REVIEW

**Comment by VictoriaMironova** [comment]
Please provide both links for manual and auto deploy

**Review by NikiforovaDaria — COMMENTED** [review]
Could you please make UI changes in your app and provide the link with changes.
Just to be sure that your configure files are working ok.

**Comment by vitalytaranov** [comment]
**manual s3/CloudFront:**
http://nodejsinaws.s3-website-eu-west-1.amazonaws.com/
d3r0wq9yasyxyz.cloudfront.net

**automated s3/CloudFront:**
http://node-js-in-aws-2.s3-website-us-east-1.amazonaws.com/
https://d1s6wl39sh56na.cloudfront.net/

plus updated footer with **Copyright © Vitaly Taranov My Store 2020.** for the automated one.

thanks @VictoriaMironova @NikiforovaDaria

**Comment by DariaNikiforova94** [comment]
Thanks for links :)
It would be great if you add your changes in MainLayout.tsx file in the PR also.

**Review by NikiforovaDaria — APPROVED** [review]

**Pull request merged**
